export default {
  login: "Teitei011",
  id: 45126099,
  node_id: "MDQ6VXNlcjQ1MTI2MDk5",
  avatar_url: "https://avatars.githubusercontent.com/u/45126099?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Teitei011",
  html_url: "https://github.com/Teitei011",
  followers_url: "https://api.github.com/users/Teitei011/followers",
  following_url:
    "https://api.github.com/users/Teitei011/following{/other_user}",
  gists_url: "https://api.github.com/users/Teitei011/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Teitei011/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Teitei011/subscriptions",
  organizations_url: "https://api.github.com/users/Teitei011/orgs",
  repos_url: "https://api.github.com/users/Teitei011/repos",
  events_url: "https://api.github.com/users/Teitei011/events{/privacy}",
  received_events_url: "https://api.github.com/users/Teitei011/received_events",
  type: "User",
  site_admin: false,
  name: "Stefan Taiguara",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Just some guy who loves to learn and code",
  twitter_username: "Stefan_Taiguara",
  public_repos: 31,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2018-11-17T15:35:21Z",
  updated_at: "2021-05-26T23:17:22Z",
};
